"""empty message

Revision ID: 04369dfa42b0
Revises: 086d10514df9
Create Date: 2025-03-10 20:46:06.692365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04369dfa42b0'
down_revision = '086d10514df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('endpoint')
    # ### end Alembic commands ###
