"""empty message

Revision ID: 2103856094c8
Revises: 2e0a8be148c4
Create Date: 2025-04-06 22:31:42.027066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2103856094c8'
down_revision = '2e0a8be148c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esnpair',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_node_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ),
    sa.ForeignKeyConstraint(['storage_node_id'], ['storagenode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esnpair')
    # ### end Alembic commands ###
