"""empty message

Revision ID: 239fbfbd3d2e
Revises: cff95dbd92ef
Create Date: 2025-05-07 14:11:39.164195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239fbfbd3d2e'
down_revision = 'cff95dbd92ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledjob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_copies_on_storage', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledjob', schema=None) as batch_op:
        batch_op.drop_column('num_copies_on_storage')

    # ### end Alembic commands ###
