"""empty message

Revision ID: 529a6b3f8ede
Revises: d5d8ad58ca2e
Create Date: 2025-04-24 21:47:05.357017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529a6b3f8ede'
down_revision = 'd5d8ad58ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledjob',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=8), nullable=False),
    sa.Column('sch_datetime', sa.DateTime(), nullable=False),
    sa.Column('next_sch_datetime', sa.DateTime(), nullable=False),
    sa.Column('sch_day', sa.String(length=9), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backupjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduledjob')
    # ### end Alembic commands ###
