"""empty message

Revision ID: 58f37f858971
Revises: df9539e97b6e
Create Date: 2025-05-05 21:14:07.731805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f37f858971'
down_revision = 'df9539e97b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledjob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'endpoint', ['endpoint_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledjob', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('endpoint_id')

    # ### end Alembic commands ###
