"""empty message

Revision ID: 731889a8697b
Revises: a80d4b8797b3
Create Date: 2025-04-14 19:45:28.281120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731889a8697b'
down_revision = 'a80d4b8797b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backupjob',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_backup', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backupjob')
    # ### end Alembic commands ###
