"""empty message

Revision ID: 96e629487cc1
Revises: 731889a8697b
Create Date: 2025-04-14 21:09:31.135092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e629487cc1'
down_revision = '731889a8697b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backupjob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esnpair', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['esnpair'])
        batch_op.create_foreign_key(None, 'esnpair', ['esnpair'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backupjob', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('esnpair')

    # ### end Alembic commands ###
