"""empty message

Revision ID: aa263b13c07c
Revises: 8ffc70a56a1c
Create Date: 2025-04-25 14:05:19.980396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa263b13c07c'
down_revision = '8ffc70a56a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledjob',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=8), nullable=False),
    sa.Column('sch_datetime', sa.DateTime(), nullable=False),
    sa.Column('next_sch_datetime', sa.DateTime(), nullable=True),
    sa.Column('sch_day', sa.String(length=9), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['backupjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduledjob')
    # ### end Alembic commands ###
