"""empty message

Revision ID: cff95dbd92ef
Revises: 58f37f858971
Create Date: 2025-05-07 12:57:37.006615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff95dbd92ef'
down_revision = '58f37f858971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backupjob',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('esnpair', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('last_backup', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['esnpair'], ['esnpair.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scheduledjob',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=8), nullable=False),
    sa.Column('sch_datetime', sa.DateTime(), nullable=False),
    sa.Column('next_sch_datetime', sa.DateTime(), nullable=True),
    sa.Column('sch_day', sa.String(length=9), nullable=True),
    sa.Column('num_archive_copies', sa.Integer(), nullable=False),
    sa.Column('last_copy_name', sa.String(length=255), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['backupjob.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduledjob')
    op.drop_table('backupjob')
    # ### end Alembic commands ###
